repos:
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E24,E121,E123,E126,E203,E226,E704,E731,W503,W504"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        args: []
        exclude: "^test/data/.*$"
        additional_dependencies:
          - "types-markdown==3.3.12"
          - "types-pyyaml==6.0.5"
          - "types-jinja2==2.11.9"
          - "types-docopt==0.6.6"
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: poetry run python -m unittest discover
        language: system
        types:
          - python
        pass_filenames: false
