repos:
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        args: []
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: poetry run python -m unittest discover
        language: system
        types:
          - python
        pass_filenames: false
