name: Deploy site to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U obraz
          npm install -g less
      - name: Build site with Obraz
        working-directory: ./doc
        run: |
          obraz build --trace
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_site
          cname: obraz-new.pirx.ru
